name: Cria_Artefato

on:
  push:
  
jobs:
  Cria_Artefato:
    name: Cria_Artefato
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
  
      - name: Upload_Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name:  ${{ vars.Artefato_Exercicio_2 }}
          path: .
